# Generated by Django 5.2.1 on 2025-06-16 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_completo', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('possui_veiculo', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], max_length=3)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('email_enviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoQualificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('area_formacao', models.CharField(choices=[('QUIMICA', 'Química'), ('BIOLOGIA', 'Biologia'), ('MEIO_AMBIENTE', 'Meio Ambiente'), ('LOGISTICA', 'Logística'), ('COMERCIAL', 'Comercial'), ('OUTROS', 'Outros')], max_length=35)),
                ('text_formacao', models.CharField(blank=True, null=True)),
                ('grau_formacao', models.CharField(choices=[('ENSINO_MEDIO', 'Ensino Médio'), ('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('GRADUACAO', 'Graduação'), ('POS_GRADUACAO', 'Pós-Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=30)),
                ('possui_registro_conselho_classe', models.CharField(choices=[('NAO_POSSUI', 'Não Possui'), ('CRQ', 'CRQ'), ('CRBIO', 'CRBio'), ('CREA', 'CREA'), ('OUTRO', 'Outro')], max_length=30)),
                ('numero_registro_conselho_classe', models.CharField(blank=True, max_length=30, null=True)),
                ('registro_ativo_conselho_classe', models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], max_length=3)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('distancia_km', models.IntegerField(blank=True, null=True)),
                ('distancia_tempo', models.CharField(blank=True, max_length=255, null=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
    ]
