# Generated by Django 5.2.1 on 2025-05-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formacaoqualificacao",
            name="text_formacao",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacaoqualificacao",
            name="area_formacao",
            field=models.CharField(
                choices=[
                    ("Química", "Quimica"),
                    ("Biologia", "Biologia"),
                    ("Meio Ambiente", "Meio Ambiente"),
                    ("Logística", "Logistica"),
                    ("Comercial", "Comercial"),
                    ("Outros", "Outros"),
                ],
                max_length=30,
            ),
        ),
    ]
