# Generated by Django 5.2.1 on 2025-06-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='possui_veiculo',
            field=models.CharField(choices=[('NAO', 'Não'), ('SIM', 'Sim')], max_length=3),
        ),
    ]
