# Generated by Django 5.2.1 on 2025-05-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='possui_veiculo',
            field=models.BooleanField(help_text='Marque "Sim" se você possui veículo, "Não" caso contrário.', verbose_name='Possui veículo?'),
        ),
    ]
