# Generated by Django 5.2.1 on 2025-06-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_possui_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='situacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=50),
        ),
    ]
