# Generated by Django 5.2.1 on 2025-06-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_email_enviado_alter_pessoa_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='distancia_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='distancia_tempo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
