# Generated by Django 5.2.1 on 2025-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_endereco_distancia_km_endereco_distancia_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='distancia_tempo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
