# Generated by Django 5.2.1 on 2025-05-27 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_empresarial', models.CharField(max_length=120)),
                ('tempo_mei', models.DateField()),
                ('possui_conta_pj', models.BooleanField()),
                ('cnae_principal', models.CharField(max_length=255)),
                ('cnae_secundario', models.CharField(max_length=255)),
                ('prestou_servicos_mei', models.BooleanField()),
                ('servicos_prestados', models.TextField(blank=True, null=True)),
                ('possui_disponibilidade_servicos_eventuais', models.BooleanField()),
                ('possui_smartphone', models.BooleanField()),
                ('atuou_em_laboratorio_analise_ambiental', models.BooleanField()),
                ('possui_cursos_area_ambiental', models.BooleanField()),
                ('cursos_realizados', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('area_interesse', models.ManyToManyField(to='fornecedores.areainteresse')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
    ]
