# Generated by Django 5.2.1 on 2025-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0002_alter_fornecedor_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="cnae_principal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="cnae_secundario",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="nome_empresarial",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="tempo_mei",
            field=models.DateField(blank=True, null=True),
        ),
    ]
